services:
  whois:
    build: ./whois
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./whois:/whois
    ports:
      - 8001:8000
  telegram:
    build: ./telegram
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./telegram:/telegram
      - ./common:/telegram/common:ro
    ports:
      - 8002:8000
    environment:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
    depends_on:
      orchestrator:
        condition: service_healthy
  vk:
    build: ./vk
    command: python app/vk.py
    volumes:
      - ./vk:/vk
      - ./common:/vk/common:ro
    ports:
      - 8003:8000
    environment:
      - VK_API_ACCESS_TOKEN
      - VK_API_VERSION
    depends_on:
      orchestrator:
        condition: service_healthy
  youtube:
    build: ./youtube
    command: python app/youtube.py
    volumes:
      - ./youtube:/youtube
      - ./common:/youtube/common:ro
    environment:
      - YOUTUBE_API_KEY
    depends_on:
      orchestrator:
        condition: service_healthy
  rabbitmq:
    build: ./rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      retries: 10
  postgres:
    image: postgres:15.2
    environment:
      - PGUSER
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
  orchestrator:
    build: ./orchestrator
    volumes:
      - type: bind
        source: ./orchestrator
        target: /orchestrator
    ports:
      - 8081:8081
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8082/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    depends_on:
      - whois
      - telegram
      - vk
      - youtube
